before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: msfSXgZUaV1fvsezBnh+jbZOBJoNNLBV0tZ8YHuDs0c2kGLReYrgR4GCDSk6wdHrHYqVXZ1uIiSCG2SBrDSCbQU+F9SJGd6Mp31qEvp0WXngYHSgQHLn8JeGVSHSX1mbzGh5zCN0WDBNfwdoM3M3ZNWsIIkM6jctgM8sWagqmvqM2XDHTJU5tO/D7vIrFjeZQJxj2hBgLXqlfNKuRP1ti9Omh2eAsBLuYdeoZh/D9Siy7AGw46v3ihtaorZw4Jt2K0CISeGrw1MhrNOXG8uWjtXpbkWxS1jQ5RGoj5KrrGEkhcL5kn5GazSwo7L7hYWL7kBTzACGuF0GXtx0TJG+HRjvtJsGzf5poi96yBAtHBwLqXgYVeplvCxIBxUipOJ7ImsWknXaQrNfADfI6Qpjc5sUIyiYbSvNsaJbFnr2GHszI/OZZIb7TB4iZ0+XLvvS9usvMlzXw/+wZjMn/sTvOtjmTmI0Y/Y9I/jaLP1hMjnNBanabZ1iQ3TAF802kMxzkjcrJmmGVo7Jz9dniupX7zB9YrwsjuoYYwnKUm9QMOlpuOpQfgJtwP7Zo3whddRAZLm9/pTR00sjR/S8b3C+PhCpMDpPkOYmjVCBrNEQG9mHUGdwzvY0cZwGBvYA1j2Mf37+zfqezHlc/CieJV+s1rw7TDPpZ1f2Hc5HgxhcsBU= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
